# Generated by Django 5.0.6 on 2024-06-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20)),
                ('course_id', models.IntegerField()),
                ('department', models.CharField(max_length=20)),
                ('no_of_students', models.IntegerField()),
                ('description', models.CharField(max_length=28)),
                ('class_name', models.CharField(max_length=20)),
                ('class_id', models.IntegerField()),
                ('creation_date', models.IntegerField()),
                ('teacher_name', models.CharField(max_length=25)),
                ('teacher_id', models.IntegerField()),
            ],
        ),
    ]
